package game.enums;

public enum Efeitos {
    FORTACELER_UNIDADES_ALIADAS,
    FORTALECER_UMA_UNIDADE,
    DESTRUIR_MOSTRO_E_COLOCAR_NA_MAO,
    CURAR_UNIDADE_ALIADA,
    DOBRAR_ATAQUE_E_DEFESA_UNIDADE_ALIADA,
    COMBATE_IMEDIATO,
    ATACAR_O_NEXUS,
    ATACA_TODOS,
    AO_SER_DESTUIDO_COMPRA_CARTA,
    ZERA_PODER,
    CRIA_BARREIRA_DE_PROTECAO_DE_DANO,
    DANO_N_AO_NEXUS
}
